apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tekton-tools
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tekton-tools
    app.kubernetes.io/part-of: tekton-tools
  name: tekton-tools
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: tekton-tools
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tekton-tools
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
