apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/gbenhaim-tenant/tekton-tools/test-container@sha256:f1e8648d35729e8aa99f7c37c4c7452c5101c4297069da77005e1edd1380b5fd
        name: container-image
        resources: {}
status: {}
