apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-container
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-container
    app.kubernetes.io/part-of: tekton-tools
  name: test-container
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-container
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-container
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/gbenhaim-tenant/tekton-tools/test-container@sha256:f1e8648d35729e8aa99f7c37c4c7452c5101c4297069da77005e1edd1380b5fd
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
